import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { store } from "../store"; // Adjust the import path according to your project structure
import ReduxProvider from "./providers/ReduxProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
